leftnav:
- identifier: 5e3e7c74-5a38-4d45-ad7d-78e7e1eaedb0
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 035994aa-68b0-4602-8ac5-cedd472369fa
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  name: 'Unit 1: Probability'
  pageRef: /pages/unit-1-probability
  weight: 30
- identifier: 2b028d93-8561-4c84-9ece-b01d0c4f191a
  name: 'Unit 2: Statistics: Bayesian Inference'
  pageRef: /pages/unit-2-statistics-bayesian-inference
  weight: 40
- identifier: d1616c8c-ad0b-4679-b5a8-4001eaeef45a
  name: 'Unit 3: Statistics: Frequentist Inference: NHST'
  pageRef: /pages/unit-3-statistics-frequentist-inference-nhst
  weight: 50
- identifier: c87974e0-c253-4a50-8148-0b92730b0131
  name: 'Unit 4: Statistics: Confidence Intervals; Regression'
  pageRef: /pages/unit-4-statistics-confidence-intervals-regression
  weight: 60
- identifier: 9df38ae8-8eec-4d2f-b7b4-815ce150cde3
  name: 'Topic 1: Introduction to Probability and Statistics'
  pageRef: /pages/class-1-counting
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 10
- identifier: 46c30d37-7fca-4bd6-9a53-cb110f972269
  name: 'Topic 2: Probability Basics'
  pageRef: /pages/class-2-probability-basics
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 20
- identifier: 68048afa-26e2-428c-bf6f-d8afc30d8591
  name: R Tutorial
  pageRef: /pages/r-tutorial
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 30
- identifier: 3bbba20b-8672-4860-bd8e-7fb2bf959551
  name: 'Studio 1: Birthday Matches'
  pageRef: /pages/studio-1-birthday-matches
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 40
- identifier: 8a3d0781-0a48-4b02-b4ff-0d32d28b65c3
  name: 'Topic 3: Conditional Probability, Independence, Bayes Theorem'
  pageRef: /pages/class-3-conditional-probability-independence-bayes-theorem
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 50
- identifier: 292aeda9-41c3-4564-8e4e-6d5b520817be
  name: 'Topic 4: Discrete Random Variables, Expected Value'
  pageRef: /pages/class-4-discrete-random-variables-expected-value
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 60
- identifier: 10608875-7568-495a-b18d-cde926f70ebc
  name: Studio 2
  pageRef: /pages/studio-2
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 70
- identifier: eaac4d85-5a08-4669-97eb-77690443503d
  name: 'Topic 5: Variance of Discrete Variables; Continuous Random Variables'
  pageRef: /pages/class-5-variance-of-discrete-variables-continuous-random-variables
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 80
- identifier: 3f2b3c6b-c3da-4b98-89d9-a6c97ae7a291
  name: Studio 3
  pageRef: /pages/studio-3
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 90
- identifier: 7d8482d3-43d4-4b77-b26f-88502e283313
  name: 'Topic 6: Continuous Random Variables: Expected Value and Variance; Histograms'
  pageRef: /pages/class-6-continuous-random-variables-expected-value-and-variance-histograms
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 100
- identifier: 1f1656e0-4d58-4835-af92-224b5f36ab0b
  name: 'Topic 6.1: Title?'
  pageRef: /pages/topic-61-title
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 110
- identifier: e729658e-8ea1-41db-87c3-ab5611b4075a
  name: 'Topic 6.2: Law of Large Numbers, Central Limit Theorem, and Histograms'
  pageRef: /pages/class-62-law-of-large-numbers-central-limit-theorem-and-histograms
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 120
- identifier: 74a3de58-e4e8-4eae-8aef-497a93af2028
  name: 'Topic 7: Joint Distributions: Independence, Covariance and Correlation'
  pageRef: /pages/class-7-joint-distributions-independence-covariance-and-correlation
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 130
- identifier: ec1e33f0-a454-45c4-80ef-fb58703d8516
  name: Studio 4
  pageRef: /pages/studio-4
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 140
- identifier: fc5d678a-adf8-48f2-b121-f94e2fd28699
  name: 'Topic 8: Exam 1 Review'
  pageRef: /pages/class-8-exam-1-review
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 150
- identifier: 60b6afbc-30d9-4852-ad59-e669be63c8f1
  name: Exam 1
  pageRef: /pages/exam-1
  parent: 3cf40710-80c3-49ae-9e83-8c9d13bf6a62
  weight: 160
